schema_version = "1.0.0"

id = "retopo_kit"
version = "1.0.0"
name = "Retopo Kit"
tagline = "One press from sculpt to game-ready"
maintainer = "Luqman Hakeem <academy@todak.com>"
type = "add-on"

website = "https://github.com/juslangit/retopo-kit"
tags = ["Mesh", "Modeling"]

blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
